version: "3"
services:
  api-jwt:
    image: api-jwt
    ports:
      - "8080:8080"
    networks:
      - crm-spring-boot-mysql
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/crm-spring-boot?useSSL=false

  mysqldb:
    image: mysql:8
    networks:
      - crm-spring-boot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crm-spring-boot

networks:
  crm-spring-boot-mysql: